"""
tools/prepare_release_assets.py
--------------------------------
Build-machine helper: run once per Chromium revision (i.e. after
`playwright install chromium` on a new Playwright version), BEFORE building
the exe / installer. It

  1. finds this machine's Playwright copy of Chromium,
  2. writes installer_paths.iss next to installer.iss, so Inno Setup picks the
     browser straight out of the Playwright folder (no 400 MB copy into the
     project folder), and
  3. builds chromium-<rev>-win64.zip — the file the app downloads if the
     browser is ever missing — and pins its SHA-256 into browser_setup.py.

Then publish the zip once as a GitHub Release asset on the tag
chromium-<rev> (the command is printed at the end). It is a separate tag
from the app releases, so it never becomes "latest".

Usage:   python tools/prepare_release_assets.py [--out DIR]
"""

import argparse
import hashlib
import os
import re
import sys
import zipfile
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT))

from browser_setup import required_revision, REPO   # noqa: E402


def find_chrome_dir(rev: str) -> Path:
    import playwright
    base = Path(playwright.__file__).parent / "driver" / "package" / ".local-browsers"
    chrome_dir = base / f"chromium-{rev}" / "chrome-win64"
    if not (chrome_dir / "chrome.exe").is_file():
        sys.exit(f"\nChromium {rev} isn't installed for this Playwright:\n  {chrome_dir}\n"
                 f"Run this first, then try again:\n"
                 f"    set PLAYWRIGHT_BROWSERS_PATH=0\n    playwright install chromium\n")
    return chrome_dir


def build_zip(chrome_dir: Path, zip_path: Path):
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    if zip_path.exists():
        zip_path.unlink()
    files = [p for p in chrome_dir.rglob("*") if p.is_file()]
    print(f"Zipping {len(files)} files from {chrome_dir} ...")
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for i, p in enumerate(files, 1):
            z.write(p, Path("chrome-win64") / p.relative_to(chrome_dir))
            if i % 100 == 0:
                print(f"  {i}/{len(files)}")


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def pin_hash(rev: str, digest: str):
    path = PROJECT / "browser_setup.py"
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(r'(CHROMIUM_ZIP_SHA256 = \{[^}]*?)"%s":\s*"[0-9a-fA-F]*"' % re.escape(rev), re.S)
    if pattern.search(text):
        text = pattern.sub(lambda m: f'{m.group(1)}"{rev}": "{digest}"', text, count=1)
    else:
        text = text.replace("CHROMIUM_ZIP_SHA256 = {", f'CHROMIUM_ZIP_SHA256 = {{\n    "{rev}": "{digest}",', 1)
    path.write_text(text, encoding="utf-8")


def main():
    default_out = Path(os.environ.get("LOCALAPPDATA", str(Path.home()))) / "Command Center build assets"
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=default_out,
                    help=f"where to put the zip (default: {default_out})")
    args = ap.parse_args()

    rev = required_revision()
    chrome_dir = find_chrome_dir(rev)

    inc = PROJECT / "installer_paths.iss"
    inc.write_text(
        "; Generated by tools/prepare_release_assets.py - machine-specific, not committed.\n"
        f'#define ChromiumRev "{rev}"\n'
        f'#define ChromiumSrcDir "{chrome_dir}"\n', encoding="utf-8")
    print(f"Wrote {inc}")

    zip_path = args.out / f"chromium-{rev}-win64.zip"
    build_zip(chrome_dir, zip_path)
    digest = sha256_of(zip_path)
    pin_hash(rev, digest)
    size_mb = zip_path.stat().st_size / (1024 * 1024)
    print(f"\nZip: {zip_path}  ({size_mb:.0f} MB)\nSHA-256: {digest}\n"
          f"Pinned into browser_setup.py (CHROMIUM_ZIP_SHA256[{rev!r}]).\n\n"
          f"Publish it once (skip if the chromium-{rev} release already has this exact file):\n"
          f'    gh release create chromium-{rev} "{zip_path}" --repo {REPO} '
          f'--title "Browser {rev} (for first-run download)" '
          f'--notes "Chromium {rev} for Command Center. Downloaded automatically by the app if the '
          f'browser is missing; not an app release." --latest=false\n')


if __name__ == "__main__":
    main()
